### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by yunarta** [yunarta/terraform-provider-bamboo#9]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-bamboo_v1.4.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102c1a358]

goroutine 16 [running]:
github.com/yunarta/terraform-provider-bamboo/provider.(*LinkedRepositoryResource).Update(0x140004eb100, {0x102ee2aa8, 0x14000547c80}, {{{{0x102ee7038, 0x14000691320}, {0x102de9d80, 0x14000563ad0}}, {0x102ee88e0, 0x14000162820}}, {{{0x102ee7038, ...}, ...}, ...}, ...}, ...)
        github.com/yunarta/terraform-provider-bamboo/provider/resource_bamboo_linked_repository.go:248 +0x158
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).UpdateResource(0x1400033c1a0, {0x102ee2aa8, 0x14000547c80}, 0x140003d1330, 0x140003d1240)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_updateresource.go:122 +0x564
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x140003d1450?, {0x102ee2aa8, 0x14000547c80}, 0x14000550460, 0x140003d1450)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_applyresourcechange.go:102 +0x118
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x1400033c1a0, {0x102ee2aa8?, 0x14000547b60?}, 0x140005503c0)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/proto6server/server_applyresourcechange.go:55 +0x314
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x14000242640, {0x102ee2aa8?, 0x140005471a0?}, 0x14000388150)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x102eb4f00?, 0x14000242640}, {0x102ee2aa8, 0x140005471a0}, 0x140004ea800, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400019b000, {0x102ee2aa8, 0x14000547110}, {0x102ee7a48, 0x140004024e0}, 0x1400054b200, 0x14000325170, 0x103391e38, 0x0)
        google.golang.org/grpc@v1.60.1/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x1400019b000, {0x102ee7a48, 0x140004024e0}, 0x1400054b200)
        google.golang.org/grpc@v1.60.1/server.go:1783 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.1/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 52
        google.golang.org/grpc@v1.60.1/server.go:1027 +0x138

Error: The terraform-provider-bamboo_v1.4.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by yunarta** [comment]
Crash happens because the update is looking with plan name, instead of state name
But anyway, we cannot update LinkedREpository

**Comment by yunarta** [comment]
issue fixed
